services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && npx turbo run build --filter=!@n8n/chat
    startCommand: npm run start:default
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: NODE_ENV
        value: "production"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-hblg.onrender.com
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"

      # === ðŸ§  Configuration de la base PostgreSQL ===
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d48gumumcj7s73dve700-a
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_a9m3
      - key: DB_POSTGRESDB_USER
        value: n8n_a9m3_user
      - key: DB_POSTGRESDB_PASSWORD
        value: pWrngGaT7P75fv2XyZ7DdVVjrB0fmR1W
      - key: DB_POSTGRESDB_SSL_CA
        value: "false"   # tu peux laisser "false" pour Render gratuit
